# Generated by Django 4.2.4 on 2023-08-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planetarium", "0003_alter_reservation_options_alter_ticket_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="astronomyshow",
            name="themes",
            field=models.ManyToManyField(to="planetarium.showtheme"),
        ),
    ]
